### ISSUE TITLE
notImplementedError

### ISSUE THREAD

**Issue by Teddyz** [claws/adsb#2]
I tried your code, without any changes, but stumbled into an error I do not understand:

```
E:\Download\Programmering\Python\adsb>sbs-client.py
Traceback (most recent call last):
  File "E:\Download\Programmering\Python\adsb\sbs-client.py", line 107, in <module>
    loop.add_signal_handler(signum, handler)
  File "C:\Program Files (x86)\Python38-32\lib\asyncio\events.py", line 536, in add_signal_handler
    raise NotImplementedError
NotImplementedError
```

I have a dump1090 running on localhost. 
Thanks!

**Comment by claws** [comment]
I'm assuming that it is because signal handlers are not supported on Windows.

The most minimal workaround I can think of would be to comment out the line 120 which is attempting to register a signal handler.
```python
loop.add_signal_handler(signum, handler)
```

There is a cleaner solution which gets which platform you are on but try this for now.

**Comment by Teddyz** [comment]
I tried to comment out the 'add_signal_handler'-row, and the program started.
I can see that it is connected to the TCP port and is receiving data. But no output is seen.

Great if you can find a simple fix for this.

**Comment by claws** [comment]
Looking back to the example in your first post it does not look like you supply the ``--raw`` or ``--processed`` command line flag. You need at least one of those to get the example script to dump either raw or processed message data to the terminal.

Take a look at the docstring at the top of the ``sbs-client.py`` file for more detailed examples.

Use ``python sbs-client.py -h`` to dump script help info.

**Comment by Teddyz** [comment]
I got data output. I was missing --raw argument. Thank you!
