### ISSUE TITLE
Input in the Module of adsb library

### ISSUE THREAD

**Issue by faheem1302** [claws/adsb#4]
i have a hex string of 28 bytes of adsb data. I am not able to use it in the modules.

e.g : adsb.sbs.aircraft.Aircraft(?????)

**Comment by claws** [comment]
Yeah, this library is currently focused on working with ADSB messages produced by software that provides BaseStation-like output. Perhaps [PyModeS](https://github.com/junzis/pyModes) might have what you are after.

**Comment by faheem1302** [comment]
Thank You!! PyModeS worked fine. I need to have my data in cat 21 asterix category(https://www.eurocontrol.int/publication/cat021-eurocontrol-specification-surveillance-data-exchange-asterix-part-12-category-21). While i decoded most of the parameters of the format.There are some i couldn't find.Have you noticed them


Surface Capabilities and Characteristics | Operational capabilities of the aircraft while on the ground.
Data Ages | Ages of the data provided.
Receiver ID | Designator of Ground Station in Distributed System.
Target Report Descriptor | Type and characteristics of the data as transmitted by a system.
Time of Applicability for Position | Time of applicability of the reported position, in the form of elapsed time since last midnight, expressed as UTC.
Time of Applicability for Velocity | Time of applicability (measurement) of the reported velocity, in the form of elapsed time since last midnight, expressed as UTC.
Geometric Height
